# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/school/senior/fall/hscd/final_project/final_project.srcs/sources_1/bd/dma_and_vga_out/ip/dma_and_vga_out_processing_system7_0_0/dma_and_vga_out_processing_system7_0_0.xci
# IP: The module: 'dma_and_vga_out_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/school/senior/fall/hscd/final_project/final_project.srcs/sources_1/bd/dma_and_vga_out/ip/dma_and_vga_out_processing_system7_0_0/dma_and_vga_out_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_and_vga_out_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/school/senior/fall/hscd/final_project/final_project.srcs/sources_1/bd/dma_and_vga_out/ip/dma_and_vga_out_processing_system7_0_0/dma_and_vga_out_processing_system7_0_0.xci
# IP: The module: 'dma_and_vga_out_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/school/senior/fall/hscd/final_project/final_project.srcs/sources_1/bd/dma_and_vga_out/ip/dma_and_vga_out_processing_system7_0_0/dma_and_vga_out_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_and_vga_out_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
