webtalk_init -webtalk_dir f:/school/2018-2019/fall/hscd/lab2part2/lab2part2.tmp/light_counter_v1_0_project/light_counter_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/light_counter_v1_0_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Oct 26 00:50:56 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d140576c4c355d4488720dfdca82e40a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2d37c7a8a9f140aa95d04ccdc1d312a7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3300 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "200 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5572_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2917461706 -regid "211395084_0_0_344" -xml f:/school/2018-2019/fall/hscd/lab2part2/lab2part2.tmp/light_counter_v1_0_project/light_counter_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/light_counter_v1_0_behav/webtalk/usage_statistics_ext_xsim.xml -html f:/school/2018-2019/fall/hscd/lab2part2/lab2part2.tmp/light_counter_v1_0_project/light_counter_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/light_counter_v1_0_behav/webtalk/usage_statistics_ext_xsim.html -wdm f:/school/2018-2019/fall/hscd/lab2part2/lab2part2.tmp/light_counter_v1_0_project/light_counter_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/light_counter_v1_0_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
