# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/school/2018-2019/fall/hscd/lab2part2/lab2part2.srcs/sources_1/bd/flash_lights/ip/flash_lights_axi_gpio_0_0/flash_lights_axi_gpio_0_0.xci
# IP: The module: 'flash_lights_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/school/2018-2019/fall/hscd/lab2part2/lab2part2.srcs/sources_1/bd/flash_lights/ip/flash_lights_axi_gpio_0_0/flash_lights_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'flash_lights_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/school/2018-2019/fall/hscd/lab2part2/lab2part2.srcs/sources_1/bd/flash_lights/ip/flash_lights_axi_gpio_0_0/flash_lights_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'flash_lights_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/school/2018-2019/fall/hscd/lab2part2/lab2part2.srcs/sources_1/bd/flash_lights/ip/flash_lights_axi_gpio_0_0/flash_lights_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'flash_lights_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/school/2018-2019/fall/hscd/lab2part2/lab2part2.srcs/sources_1/bd/flash_lights/ip/flash_lights_axi_gpio_0_0/flash_lights_axi_gpio_0_0.xci
# IP: The module: 'flash_lights_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/school/2018-2019/fall/hscd/lab2part2/lab2part2.srcs/sources_1/bd/flash_lights/ip/flash_lights_axi_gpio_0_0/flash_lights_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'flash_lights_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/school/2018-2019/fall/hscd/lab2part2/lab2part2.srcs/sources_1/bd/flash_lights/ip/flash_lights_axi_gpio_0_0/flash_lights_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'flash_lights_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/school/2018-2019/fall/hscd/lab2part2/lab2part2.srcs/sources_1/bd/flash_lights/ip/flash_lights_axi_gpio_0_0/flash_lights_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'flash_lights_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
