# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/flash_lights/flash_lights.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flash_lights || ORIG_REF_NAME==flash_lights} -quiet] -quiet

# IP: bd/flash_lights/ip/flash_lights_processing_system7_0_0/flash_lights_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flash_lights_processing_system7_0_0 || ORIG_REF_NAME==flash_lights_processing_system7_0_0} -quiet] -quiet

# IP: bd/flash_lights/ip/flash_lights_light_counter_0_0/flash_lights_light_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flash_lights_light_counter_0_0 || ORIG_REF_NAME==flash_lights_light_counter_0_0} -quiet] -quiet

# IP: bd/flash_lights/ip/flash_lights_ps7_0_axi_periph_0/flash_lights_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flash_lights_ps7_0_axi_periph_0 || ORIG_REF_NAME==flash_lights_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/flash_lights/ip/flash_lights_rst_ps7_0_50M_0/flash_lights_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flash_lights_rst_ps7_0_50M_0 || ORIG_REF_NAME==flash_lights_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/flash_lights/ip/flash_lights_axi_gpio_0_0/flash_lights_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flash_lights_axi_gpio_0_0 || ORIG_REF_NAME==flash_lights_axi_gpio_0_0} -quiet] -quiet

# IP: bd/flash_lights/ip/flash_lights_xbar_0/flash_lights_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flash_lights_xbar_0 || ORIG_REF_NAME==flash_lights_xbar_0} -quiet] -quiet

# IP: bd/flash_lights/ip/flash_lights_auto_pc_0/flash_lights_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flash_lights_auto_pc_0 || ORIG_REF_NAME==flash_lights_auto_pc_0} -quiet] -quiet

# XDC: bd/flash_lights/flash_lights_ooc.xdc
