######################################################################
##
## Filename: EdgeTriggeredDFlipFlop.udo
## Created on: Wed Oct 26 11:02:29 PM Central Daylight Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
