######################################################################
##
## Filename: UpDownCounter.udo
## Created on: Wed Nov 02 10:11:57 PM Central Daylight Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
