# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/VGAconst.xdc

# Block Designs: bd/dma_and_vga_out/dma_and_vga_out.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_and_vga_out || ORIG_REF_NAME==dma_and_vga_out} -quiet] -quiet

# IP: bd/dma_and_vga_out/ip/dma_and_vga_out_vga_out_0_0/dma_and_vga_out_vga_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_and_vga_out_vga_out_0_0 || ORIG_REF_NAME==dma_and_vga_out_vga_out_0_0} -quiet] -quiet

# IP: bd/dma_and_vga_out/ip/dma_and_vga_out_processing_system7_0_0/dma_and_vga_out_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_and_vga_out_processing_system7_0_0 || ORIG_REF_NAME==dma_and_vga_out_processing_system7_0_0} -quiet] -quiet

# IP: bd/dma_and_vga_out/ip/dma_and_vga_out_ps7_0_axi_periph_0/dma_and_vga_out_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_and_vga_out_ps7_0_axi_periph_0 || ORIG_REF_NAME==dma_and_vga_out_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/dma_and_vga_out/ip/dma_and_vga_out_rst_ps7_0_50M_0/dma_and_vga_out_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_and_vga_out_rst_ps7_0_50M_0 || ORIG_REF_NAME==dma_and_vga_out_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/dma_and_vga_out/ip/dma_and_vga_out_auto_pc_0/dma_and_vga_out_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_and_vga_out_auto_pc_0 || ORIG_REF_NAME==dma_and_vga_out_auto_pc_0} -quiet] -quiet

# XDC: bd/dma_and_vga_out/dma_and_vga_out_ooc.xdc
